teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4
    scale_angular_turbo:
      yaw: 0.8

    enable_turbo_button: 6  # L1 shoulder button
    require_enable_button: false # don't require an enable button
